version: '3.8'

services:
  byebg:
    build: 
      context: .
      target: base
    command: 'python ./src/byebg.py ./img/gabriel_vanessa.jpg ./img/gabriel_vanessa_byebg.png'
    volumes:
      - './img:/opt/python/img'
